name: "Lint Checks"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Basic linter check
  lint-check:
    name: Lint check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "24"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run formatter check
        run: |
          ./node_modules/.bin/prettier --check --loglevel silent "src/**/*.ts" || ( \
            echo "Run this command on your local device to fix the error:" && \
            echo "" && \
            echo "  make format" && \
            echo "" && exit 1)

      - name: Run build check
        run: |
          npm run build && test -z "$(git status --porcelain)" || ( \
            echo "dist is out of date, run this command on your local device to fix the error:" && \
            echo "" && \
            echo "  make build" && \
            echo "" && exit 1)
